### ISSUE TITLE
Support for other types of proc-macros?

### ISSUE THREAD

**Issue by mxxo** [bbqsrc/cargo-proc-macro#1]
Would you be interested in reviewing PRs to add support for function-like and derive-macros as well?
It might complicate the command-line interface a bit but I think it could be useful. 

We could have some optional arguments like: 
```shell
cargo proc-macro new some_dir --function=some_macro --attr=some_attr --derive=some_derive
```

with `attr` being the default like it is now.

**Comment by bbqsrc** [comment]
Hey @mxxo! Sorry about the delay, I never got a notification for this issue 😲 

I am very happy to support the other types of proc macro, yes!

I have opinions about the actual command line interface, but getting the functionality is a much more important first step than the bikeshedding over CLI. :smile:

Let me know if you're still interested and need some guidance.

**Comment by mxxo** [comment]
Hi @bbqsrc, no problem at all. I'd still be interested in trying this :). 

My plan was: 
* add new [`{BASE, CRATE}_IMPLs`](https://github.com/bbqsrc/cargo-proc-macro/blob/master/src/cli.rs#L80)
* adjust the CLI to expose the new proc-macro generators. 

I am a little bit confused about the two crate output and would have expected just the one crate.

**Comment by bbqsrc** [comment]
Basically, due to the fact that `proc_macro` isn't particularly easily testable in isolation, `proc_macro2` implements the entire API of it so we can do just that. This means in practice we need a stub crate with the "real" macro and then a library crate with its actual guts.

Your plan sounds great. 😄

**Comment by mxxo** [comment]
What makes the two-crate solution (sorry) better than a single crate? I think you can test, have internal modules etc in a "real" proc-macro crate.

I can see the macro-writing process might be nicer, i.e. users are greeted with a clean prompt: 
```rust
use proc_macro2::TokenStream;
use quote::quote;

pub fn new_mac(attr: TokenStream, item: TokenStream) -> Result<TokenStream, syn::Error> {
    // Implement your proc-macro logic here. :)
    Ok(item)
}
```
instead of having to look at the full complexity immediately, e.g. the library and stub smushed together: 
```rust
extern crate proc_macro;

use proc_macro2::TokenStream;
use quote::quote;
use syn::parse_macro_input;

#[proc_macro_attribute]
pub fn new_mac(attr: proc_macro::TokenStream, item: proc_macro::TokenStream) -> proc_macro::TokenStream {
    let attr = parse_macro_input!(attr as proc_macro2::TokenStream);
    let item = parse_macro_input!(item as proc_macro2::TokenStream);

    match new_mac_impl(attr, item) {
        Ok(tokens) => tokens.into(),
        Err(err) => proc_macro::TokenStream::from(err.to_compile_error()),
    }
}

fn new_mac_impl(attr: TokenStream, item: TokenStream) -> Result<TokenStream, syn::Error> {
    // Implement your proc-macro logic here. :)
    Ok(item)
}
```

but this approach lets us skip the workspace and the second crate.

**Comment by bbqsrc** [comment]
The only remaining aspect is the question of the multiple crate approach, and there's some prior art as to why I do this, and other crates do it too, but I haven't had much time to track those down. The only one I can think of is serde and it does a rather complicated method for it. 

A nicer approach is https://github.com/dtolnay/inventory which nests an `impl` directory with the stuff and a `src` dir as the entry point... Hmm. Maybe we want to wander down this path?

**Comment by mxxo** [comment]
> A nicer approach is https://github.com/dtolnay/inventory which nests an impl directory with the stuff and a src dir as the entry point... Hmm. Maybe we want to wander down this path?

Personally I think this would be worthwhile just to avoid splitting the proc-macro implementation in two (makes publishing easier etc.) I could open another issue specific to the output workspace structure to finish up this issue.

I am happy to defer to your decision here and don't want to disrupt your workflow.

**Comment by bbqsrc** [comment]
I don't have a workflow, this is a collaborative effort. :smile:

If you want to muck around with doing something like inventory, I think it'd be great too. 👍

**Comment by bbqsrc** [comment]
Oh and yes, open an issue for that so we can close this one. (I'm in a meeting atm so a bit spaced out, hehe)
