### ISSUE TITLE
Output workspace structure

### ISSUE THREAD

**Issue by mxxo** [bbqsrc/cargo-proc-macro#5]
Investigate potential changes to the output workspace structure to make program output match exemplary proc-macros like [`inventory`](https://github.com/dtolnay/inventory) (see motivating discussion [here](https://github.com/bbqsrc/cargo-proc-macro/issues/1#issuecomment-701582439)).

**Comment by bbqsrc** [comment]
v0.2.0 now implements this. 😄

**Comment by mxxo** [comment]
Hey that's great! Guess I'll close this 😄
